# Generated by Django 3.2.9 on 2023-09-13 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Answer_rate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='Expired_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
