# Generated by Django 3.2.9 on 2023-09-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230913_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Expired_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
