# Generated by Django 3.2.9 on 2023-09-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Answer_rate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
