# Generated by Django 3.2.9 on 2023-09-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_testfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='link',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='testfile',
            old_name='link',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='link',
            new_name='file_id',
        ),
    ]
